
USE APPIASQL;
GO

DROP DATABASE IF EXISTS
[INVENTARIO];
GO

DROP PROCEDURE IF EXISTS
[CrearDATA],
[TablaCLIENTE],
[TablaCOCHE],
[TablaFACTURA],
[TablaEMPLEADO],
[TablaFACTURA_EMPLEADO],
[MATERIAL_SKU],
[TablaDISTRIBUIDOR],
[TablaLINEA_PEDIDO],
[TablaLINEA_FACTURA];
GO

DROP TABLE IF EXISTS
[COCHE],
[DISTRIBUIDOR],
[EMPLEADO],
[FACTURA],
[FACTURA_EMPLEADO],
[INV_CLIENTE],
[LINEA_FACTURA],
[LINEA_PEDIDO],
[MATERIAL_SKU],
[PEDIDO];
GO

CREATE PROCEDURE CrearDATA
AS
BEGIN
CREATE DATABASE INVENTARIO;
END
GO
EXECUTE DBO.CrearDATA
GO

USE INVENTARIO;
GO

CREATE PROCEDURE TablaCLIENTE
AS
BEGIN
CREATE TABLE INV_CLIENTE(
NroCLIENTE INT PRIMARY KEY NOT NULL,
Nombres VARCHAR(80) NOT NULL,
Apellidos VARCHAR(80) NOT NULL,
Direccion VARCHAR(80) NOT NULL,
Telefono VARCHAR(80) NOT NULL,
)
END
GO
EXECUTE DBO.TablaCLIENTE
GO

CREATE PROCEDURE TablaCOCHE
AS
BEGIN
CREATE TABLE COCHE(
NroCOCHE INT PRIMARY KEY NOT NULL,
Marca VARCHAR(80) NOT NULL,
Modelo INT NOT NULL,
Kilometros INT NOT NULL,
Foto VARCHAR(80) NOT NULL,
FKC_Cliente INT NOT NULL,
)
END
GO
EXECUTE DBO.TablaCOCHE
GO

CREATE PROCEDURE TablaFACTURA
AS
BEGIN
CREATE TABLE FACTURA(
NroFACTURA INT PRIMARY KEY NOT NULL,
Fecha DATE NOT NULL,
Estado VARCHAR(80) NOT NULL,
FKF_NroMatriula INT NOT NULL,
FKF_NroCliente INT NOT NULL,
)
END
GO
EXECUTE DBO.TablaFACTURA
GO

CREATE PROCEDURE TablaEMPLEADO
AS
BEGIN
CREATE TABLE EMPLEADO(
NroEMPLEADO INT PRIMARY KEY NOT NULL,
Nombres VARCHAR(80) NOT NULL,
Apellidos VARCHAR(80) NOT NULL,
Categoria VARCHAR(80) NOT NULL,
)
END
GO
EXECUTE DBO.TablaEMPLEADO
GO

CREATE PROCEDURE TablaFACTURA_EMPLEADO
AS
BEGIN
CREATE TABLE FACTURA_EMPLEADO(
FKF_NroEmpleado INT NOT NULL,
FKF_NroFactura INT NOT NULL,
NroHoras INT NOT NULL,
)
END
GO
EXECUTE DBO.TablaFACTURA_EMPLEADO
GO

CREATE PROCEDURE TablaMATERIAL_SKU
AS
BEGIN
CREATE TABLE MATERIAL_SKU(
NroMATERIAL_SKU INT PRIMARY KEY NOT NULL,
Stock FLOAT NOT NULL,
Descripcion VARCHAR(80) NOT NULL,
StockMinimo FLOAT NOT NULL,
PrecioUnitario FLOAT NOT NULL,
FKD_NroDistribuidor INT NOT NULL,
)
END
GO
EXECUTE DBO.TablaMATERIAL_SKU
GO

CREATE PROCEDURE TablaDISTRIBUIDOR
AS
BEGIN
CREATE TABLE DISTRIBUIDOR(
NroDISTRIBUIDOR INT PRIMARY KEY NOT NULL,
RazonSocial VARCHAR(80) NOT NULL,
Direccion VARCHAR(80) NOT NULL,
Telefono VARCHAR(80) NOT NULL,
)
END
GO
EXECUTE DBO.TablaDISTRIBUIDOR
GO

CREATE PROCEDURE TablaPEDIDO
AS
BEGIN
CREATE TABLE PEDIDO(
NroPEDIDO INT PRIMARY KEY NOT NULL,
Fecha_Solicitud DATE NOT NULL,
Fecha_Entrega DATE NOT NULL,
Actualizado VARCHAR(80) NOT NULL,
FKP_NroDistribuidor INT NOT NULL
)
END
GO
EXECUTE DBO.TablaPEDIDO
GO

CREATE PROCEDURE TablaLINEA_PEDIDO
AS
BEGIN
CREATE TABLE LINEA_PEDIDO(
FKL_NroPedido INT NOT NULL,
FKL_NroMATERIAL_SKU INT NOT NULL,
Cantidad FLOAT NOT NULL,
PVD VARCHAR(80)
)
END
GO
EXECUTE DBO.TablaLINEA_PEDIDO
GO

CREATE PROCEDURE TablaLINEA_FACTURA
AS
BEGIN
CREATE TABLE LINEA_FACTURA(
FKL_NroFactura INT NOT NULL,
FKL_NroMATERIAL_SKU INT NOT NULL,
Cantidad FLOAT NOT NULL,
PVD VARCHAR(80) NOT NULL,
)
END
GO
EXECUTE DBO.TablaLINEA_FACTURA
GO

--FK
ALTER TABLE COCHE
ADD FOREIGN KEY (FKC_Cliente) REFERENCES INV_CLIENTE(NroCLIENTE)

ALTER TABLE FACTURA
ADD FOREIGN KEY (FKF_NroCliente) REFERENCES INV_CLIENTE(NroCLIENTE)

ALTER TABLE FACTURA
ADD FOREIGN KEY (FKF_NroMatriula) REFERENCES COCHE(NroCOCHE)

ALTER TABLE FACTURA_EMPLEADO
ADD FOREIGN KEY (FKF_NroEmpleado) REFERENCES EMPLEADO(NroEMPLEADO)

ALTER TABLE FACTURA_EMPLEADO
ADD FOREIGN KEY (FKF_NroFactura) REFERENCES FACTURA(NroFACTURA)

ALTER TABLE MATERIAL_SKU
ADD FOREIGN KEY (FKD_NroDistribuidor) REFERENCES DISTRIBUIDOR(NroDISTRIBUIDOR)

ALTER TABLE PEDIDO
ADD FOREIGN KEY (FKP_NroDistribuidor) REFERENCES DISTRIBUIDOR(NroDISTRIBUIDOR)

ALTER TABLE LINEA_PEDIDO
ADD FOREIGN KEY (FKL_NroMATERIAL_SKU) REFERENCES MATERIAL_SKU(NroMATERIAL_SKU)

ALTER TABLE LINEA_PEDIDO
ADD FOREIGN KEY (FKL_NroPedido) REFERENCES PEDIDO(NroPEDIDO)


ALTER TABLE LINEA_FACTURA
ADD FOREIGN KEY (FKL_NroFactura) REFERENCES FACTURA(NroFACTURA)

ALTER TABLE LINEA_FACTURA
ADD FOREIGN KEY (FKL_NroMATERIAL_SKU) REFERENCES MATERIAL_SKU(NroMATERIAL_SKU)