
USE APPIASQL
GO

DROP PROCEDURE IF EXISTS
[EliminarDATA],
[CrearDATA],
[CrearHOTEL],
[CrearUSUARIO],
[CrearReservaVUELO],
[CrearVUELO],
[FkReservaHOTEL],
[FkUsuario],
[FkReservaUsuario],
[FkReservaVuelo];
GO

DROP TABLE IF EXISTS
[HOTEL],
[ReservaHOTEL],
[USUARIO],
[ReservaVUELO],
[VUELO];
GO

CREATE PROCEDURE EliminarDATA
AS
BEGIN
DROP DATABASE IF EXISTS [HOTEL]
END
GO
EXEC DBO.EliminarDATA
GO

CREATE PROCEDURE CrearDATA
AS
BEGIN
CREATE DATABASE [HOTEL]
END      
GO
EXEC DBO.CrearDATA;
GO

USE [HOTEL]
GO

CREATE PROCEDURE CrearHOTEL
AS
BEGIN
CREATE TABLE HOTEL(
NroHOTEL INT PRIMARY KEY NOT NULL,
NombreComercial VARCHAR(80) NOT NULL,
Direccion VARCHAR(80) NOT NULL,
FechaDeApertura VARCHAR(80) NOT NULL,
NroTorres VARCHAR(80) NOT NULL,
)
END
GO
EXEC DBO.CrearHOTEL
GO


CREATE PROCEDURE CrearUSUARIO
AS
BEGIN
CREATE TABLE USUARIO(
NroUSUARIO INT PRIMARY KEY NOT NULL,
PrimerNombre VARCHAR(80) NOT NULL,
SegundoNombre VARCHAR(80) NOT NULL,
PrimerApellido VARCHAR(80) NOT NULL,
SegundoApellido VARCHAR(80) NOT NULL,
Direccion VARCHAR(80) NOT NULL,
Nacionalidad VARCHAR(80) NOT NULL,
FechaNacimiento DATE NOT NULL,
)
END
GO
EXEC DBO.CrearUSUARIO
GO

CREATE PROCEDURE CrearReservaHOTEL
AS
BEGIN
CREATE TABLE ReservaHOTEL(
NroReservaHOTEL INT PRIMARY KEY NOT NULL,
HFkNroHOTEL INT NOT NULL,
UFkNroUsuario INT NOT NULL,
FechaInicialDeReserva DATE NOT NULL,
FechaFinalDeReserva DATE NOT NULL,
NroDias INT NOT NULL,
)
END
GO
EXEC DBO.CrearReservaHOTEL
GO


CREATE PROCEDURE CrearVUELO 
AS
BEGIN
CREATE TABLE VUELO(
NroVUELO INT PRIMARY KEY NOT NULL,
AerolineaNICIAL VARCHAR(80) NOT NULL,
AerolineaFINAL VARCHAR(80) NOT NULL,
DiaDeSalida DATE NOT NULL,
DiaDeEntrada DATE NOT NULL,
HoraDeSalida TIME NOT NULL,
HoraDeLlegada TIME NOT NULL,
NroAvion INT NOT NULL,
PlazaDeOcupacion INT NOT NULL,
)
END
GO
EXEC DBO.CrearVUELO
GO

CREATE PROCEDURE CrearReservaVUELO
AS
BEGIN
CREATE TABLE ReservaVUELO(
NroReservaVUELO INT PRIMARY KEY NOT NULL,
FechaInicial DATE NOT NULL,
FechaFinal DATE NOT NULL,
Valor FLOAT NOT NULL,
UFkNroUSUARIO INT NOT NULL,
VFkNroVUELO INT NOT NULL,
)
END
GO
EXEC DBO.CrearReservaVUELO
GO

CREATE PROCEDURE FkReservaHOTEL
AS
BEGIN
ALTER TABLE ReservaHOTEL
ADD FOREIGN KEY  (HFkNroHOTEL) REFERENCES HOTEL(NroHOTEL)
END
GO
EXEC DBO.FkReservaHOTEL
GO

CREATE PROCEDURE FkUsuario
AS
BEGIN
ALTER TABLE ReservaHOTEL
ADD FOREIGN KEY (UFkNroUsuario) REFERENCES USUARIO(NroUSUARIO)
END
GO
EXEC DBO.FkUsuario
GO

CREATE PROCEDURE FkReservaUsuario
AS
BEGIN
ALTER TABLE ReservaVUELO
ADD FOREIGN KEY (UFkNroUSUARIO) REFERENCES USUARIO(NroUSUARIO)
END
GO
EXEC DBO.FkReservaUsuario
GO

CREATE PROCEDURE FkReservaVuelo
AS
BEGIN
ALTER TABLE ReservaVUELO 
ADD FOREIGN KEY (VFkNroVUELO) REFERENCES VUELO(NroVUELO)
END
GO
EXEC DBO.FkReservaVuelo
GO